### ISSUE TITLE
Website Certificate has expired

### ISSUE THREAD

**Issue by n4hte** [busybox11/NowPlaying-for-Spotify#73]
![image](https://user-images.githubusercontent.com/29691649/164507835-a9c7ca2e-6b52-4f3f-8797-43e900ce8323.png)

**Comment by busybox11** [comment]
Yeah, I'm aware of that, and I can't do anything to that unfortunately. I've renewed the certificate on the registrar but it doesn't work.
I'm going to migrate the website on my server probably next week since it's my holidays and I'll have time to do it, but for now we have to stick with it, sorry..
