### ISSUE TITLE
Add a toggle for transparent background

### ISSUE THREAD

**Issue by VictorVerbeke** [busybox11/NowPlaying-for-Spotify#78]
**Is your feature request related to a problem? Please describe.**
I try to use it on OBS but the background gets in the way as I would like to include only the "playing-div" on OBS.

**Describe the solution you'd like**
A button (like the current background style button) to toggle the background visibility.
Default would be "on" and put the background of the background-image-div to the artwork url, and "off" would put it to background: transparent.

**Describe alternatives you've considered**
I tried custom css but it seems I cannot edit the page appearance by specifying a rgba(0,0,0,0) or transparent background for the concerned div.

**Comment by busybox11** [comment]
Fixed by https://github.com/busybox11/NowPlaying-for-Spotify/commit/8adfa68ce48d0c6b06566e5e514082250ac54fa7

You can toggle this transparent mode via the `transparent` GET URL parameter set to `true`, which will make the URL look like this:
`https://nowplayi.ng/playing.php?transparent=true`

Thank you for the submission!
